### ISSUE TITLE
sameparty condition

### ISSUE THREAD

**Issue by LcorpOfficial** [0tickpulse/lcc-mythicmobs-utilities#1]
= no resulting errors or effects

`- skill{s=TestConditionSameParty} ~onAttack`

```yml
TestConditionSameParty:
  Skills:
  - skill{s=SamePartyTestWithTarget} @Target

TestConditionSamePartyWithTarget:
  Conditions:
  - sameparty orElseCast SamePartyTestWithTargetFail
  Skills:
  - message{m=Same party} @Self

TestConditionSamePartyWithTargetFail:
  Skills:
  - message{m=Not same party} @Self
 ```
